### ISSUE TITLE
Add a pull refresh on leaderboard

### ISSUE THREAD

**Issue by SebastienBoissiere** [SSWConsulting/SSW.Consulting#32]
After getting points the leaderboard is not refreshed, we need to be able to force the refresh on pull

**Comment by MattGoldmanSSW** [comment]
Pull to refresh was added in [this commit](https://github.com/SSWConsulting/SSW.Consulting/commit/e45c51ed818de0a1f23025ff65b3b68beb45bfcc)
Update leaderboard on succesful points was added in [this commit](https://github.com/SSWConsulting/SSW.Consulting/commit/33754ff93b7f5c054bc7c5019e68d1ec5a8566f1)
